[server]
host = "0.0.0.0"
port_binance_spot = 50001
port_binance_futures = 50002
port_timebar_minutes = 50051
port_timebar_seconds = 50053
port_vpin = 50054
port_tibs = 50052
port_tibs_small = 50062
port_tibs_large = 50052
port_trbs_small = 50063
port_trbs_large = 50064
port_vibs_small = 50065
port_vibs_large = 50066
port_tick_persistence = 50091
port_bar_persistence = 50092


[influx]
url = "http://localhost:8086"
token = "prod-token"
org = "prod-org"
bucket = "raven-prod"

[timescale]
url = "postgres://user:password@db-host:5432/postgres"
schema = "warehouse"

[logging]
level = "info"

[routing]
venue_include = []
venue_exclude = []
[routing.symbol_map]
# "PEPE/USDT" = { BINANCE_FUTURES = "1000PEPEUSDT" }
