[server]
host = "0.0.0.0"
port_spot = 50051
port_futures = 50054
port_persistence = 50052
port_bars = 50053
port_tibs = 50055

[tibs]
initial_size = 100.0
initial_p_buy = 0.7
alpha_size = 0.1
alpha_imbl = 0.1
size_min = 50.0
size_max = 1000.0

[influx]
url = "http://localhost:8086"
token = "my-token"
org = "my-org"
bucket = "raven"

[logging]
level = "info"

